### PR TITLE
fileName extracted from request.URL

### PR DESCRIPTION
**Pull request by orcema**
this line of code will extract the file name from the request.url.

e.g. localhost:8080/myfile.mp3

Thus all the files within the floder will be served using this code:

  const serveRobots = fileServer.serveDirectory('D:\\tmp\\GHCache', {
    '.mp3':'audio/mpeg',
    '.gif': 'image/gif',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
  });

  require('http')
    .createServer(serveRobots)
    .listen(8080);
}

### CODE REVIEW

**Comment by KoryNunn** [comment]
Some context: We use https://www.npmjs.com/package/dion to serve files, which uses `fileServer` under the covers, and which coveres this case for us.

However, I think this is a reasonable addition, if it passes all tests, and *new tests are added for it*.

Also, please update the code to use a block (`{` `}` ) around your `if`.

Thanks for the PR!

**Comment by KoryNunn** [comment]
On second reading, this code will fail if the path is not on the root. I am now less sure about this, as it is effectively going to get into the routing space, which is not the responsibility of `fileServer`...

Interested in thoughts from @MauriceButler...

**Comment by orcema** [comment]
Hi, sorry but i don't understand the concern because when i implement file-server like here below i do not have any issue. Whatever url i request i get the file if it's present on the server and else an error about the missing file.

```
function localFileServerStart(){
  const FileServer = require('file-server');
  
  const fileServer = new FileServer((error, request, response) => {
      response.statusCode = error.code || 500;
      response.end("404: Not Found " +request.url);
  });
  
  const serveRobots = fileServer.serveDirectory(cacheFolder, {
    '.mp3':'audio/mpeg'
  });

  if (httpServer===""){
    httpServer = require('http') 
    .createServer(serveRobots)
    .listen(httpServerPort);
  } 
  
}
```

request to server:
>http://localhost:8095/dfd/subFolder/SIMPLE_TEST_7.mp3

response from server:
>404: Not Found /dfd/subFolder/SIMPLE_TEST_7.mp3

**Comment by KoryNunn** [comment]
Ah yes, the string.replace only works on the first character.

Can you please change that to a .slice(1) to make the intent more obvious, and change the if to a block.

Also please add tests for this functionality.

**Comment by KoryNunn** [comment]
I just switched this to an arg length check because it will result in more traceable errors if a developer passes `undefined` in accidentally, rather than auto-serving a file.

**Comment by KoryNunn** [comment]
Awaiting publish from @MauriceButler ...

**Comment by orcema** [comment]
have you pushed the update to the npm repository ?

**Comment by MauriceButler** [comment]
@orcema Have now. [file-server@2.1.0](https://registry.npmjs.org/file-server )

**Pull request merged**
